"""Filesystem adapter for generated build artifacts."""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path


MARKER = ".fleetctl-output"
MARKER_CONTENT = "GENERATED — DO NOT EDIT\nGenerated by fleetctl; this directory may be replaced atomically.\n"


class OutputDirectoryError(Exception):
    pass


def write_rendered_files(output: Path, files: dict[str, bytes]) -> None:
    if output.is_symlink():
        raise OutputDirectoryError(f"refusing to replace symlink output directory: {output}")
    output = output.resolve()
    if output.exists() and (not output.is_dir() or not (output / MARKER).is_file()):
        raise OutputDirectoryError(f"refusing to replace unmarked output directory: {output}")

    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}.staging-", dir=output.parent))
    backup: Path | None = None
    try:
        (staging / MARKER).write_text(MARKER_CONTENT, encoding="utf-8")
        for relative_name, content in sorted(files.items()):
            target = staging / relative_name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)

        if output.exists():
            backup = Path(tempfile.mkdtemp(prefix=f".{output.name}.backup-", dir=output.parent))
            backup.rmdir()
            output.rename(backup)
        staging.rename(output)
        if backup is not None:
            shutil.rmtree(backup)
    except Exception:
        if not output.exists() and backup is not None and backup.exists():
            backup.rename(output)
        raise
    finally:
        if staging.exists():
            shutil.rmtree(staging)


def write_generated_artifact(output: Path, relative_name: str, content: bytes) -> Path:
    if output.is_symlink():
        raise OutputDirectoryError(f"refusing to write through symlink output directory: {output}")
    output = output.resolve()
    if not output.is_dir() or not (output / MARKER).is_file():
        raise OutputDirectoryError(f"output directory is not managed by fleetctl: {output}")
    relative = Path(relative_name)
    if relative.is_absolute() or ".." in relative.parts:
        raise OutputDirectoryError(f"invalid generated artifact path: {relative_name}")
    target = output / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(prefix=f".{target.name}.", dir=target.parent, delete=False) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.replace(target)
    return target
