#!/usr/sbin/nft -f
flush ruleset
table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;
    ct state invalid drop
    ct state established,related accept
    iifname "lo" accept
    ip protocol icmp limit rate 20/second accept
    ip6 nexthdr ipv6-icmp limit rate 20/second accept

    ip saddr 206.84.238.130/32 tcp dport 22 accept
    ip saddr 10.20.0.2/32 tcp dport 22 accept

    udp dport { 51820 } accept

    tcp dport { 9090, 3100, 3000 } accept

    iifname "wg0" ip saddr 10.20.0.0/24 tcp dport { 3100, 9090 } accept
    iifname "wg0" ip saddr 10.20.0.2/32 tcp dport { 8200, 3000, 9093 } accept
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state invalid drop
    ct state established,related accept
    iifname "wg0" oifname "wg0" ip saddr 10.20.0.0/24 ip daddr 10.20.0.0/24 accept
    ip saddr 172.16.0.0/12 accept
    tcp dport { 9090, 3100, 3000 } accept
  }

  chain output { type filter hook output priority filter; policy accept; }
}
