apiVersion: spiritvpn.io/v1alpha1
kind: Environment
metadata:
  id: develop
spec:
  dns_zone: develop.example.invalid
  management_network: 10.80.0.0/16
  backend_endpoint: backend.develop.internal:9443
  secret_store:
    kv: kv/develop
    pki: pki/develop
  common_overrides:
    components:
      node_agent:
        repository: ghcr.io/spirittechdevelopment/node-agent
        digest: sha256:5e2b89734b02964669b79ce76014dada92ba58e89856fdc03b64aaebae8c8967
