---
env: dev
common_manage_deploy_user: false
common_remove_legacy_sshd_dropin: false
common_manage_sshd: false
common_manage_firewall: false
common_enable_fail2ban: false
common_manage_sysctl: false
common_enable_auditd: false
common_enable_unattended_upgrades: false
docker_manage_daemon_config: false
docker_remove_legacy_no_new_privileges: false
management_wireguard_enabled: false
xray_enable_api: true
xray_api_public_mode: true
xray_api_bind: "0.0.0.0"
xray_access_log: ""
xray_error_log: ""
xray_loglevel: debug
