apiVersion: spiritvpn.io/v1alpha1
kind: LogicalNode
metadata:
  id: develop-exit-ro
spec:
  role: exit
  region: ro
  public:
    hostname: ro.vmshare.ru
    port: 443
    transport: tcp
    flow: xtls-rprx-vision
    fingerprint: chrome
    server_name: ro.vmshare.ru
  reality:
    public_key: lMqgNaTTnkTY1Rwe-krqEFNNQKT8MzDOrxlRHVQd9Aw
    short_id: "294753b602c08325"
    private_key_ref: secret://kv/develop/nodes/develop-exit-ro/reality#private_key
  mask:
    certificate_ref: secret://kv/develop/nodes/develop-exit-ro/mask#fullchain
    private_key_ref: secret://kv/develop/nodes/develop-exit-ro/mask#private_key
  display_name: Romania
